// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjptqnpjlwpjhdnduzbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcHRxbnBqbHdwamhkbmR1emJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODcwNDMsImV4cCI6MjA2NTk2MzA0M30.89BZ75KRjg3OQZUcbYRJGBYf1s6OIRrxsBQYzwXrTP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);